require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Exclude:
    - 'lib/gobl/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/gobl/**/*.rb'

Layout/LineLength:
  Exclude:
    - 'lib/gobl/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/gobl/**/*.rb'
